import assert from 'node:assert/strict';
import { createBlankGame } from '../dist/frontend/src/types/gameModel.js';
import { execFileSync } from 'node:child_process';
const origin=process.env.TEST_ORIGIN||'http://localhost:3001';
let checks=0;
async function request(path,{method='GET',body,cookie,headers={},status=200}={}){
 const res=await fetch(origin+'/api'+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});
 const data=await res.json();assert.equal(res.status,status,path+': '+JSON.stringify(data));checks++;return {data,cookie:res.headers.get('set-cookie')?.split(';')[0],res};
}
const suffix=Date.now().toString(36),password='Testable Amber Sky '+suffix;
const a=await request('/auth/signup',{method:'POST',body:{username:'api_'+suffix,password},status:201});
const b=await request('/auth/signup',{method:'POST',body:{username:'other_'+suffix,password},status:201});
assert.match(a.res.headers.get('set-cookie'),/HttpOnly/);assert.match(a.res.headers.get('set-cookie'),/SameSite=Lax/);
const schema=createBlankGame('API verification '+suffix);
schema.scoring.winCondition='survive_time';schema.scoring.targetValue=50;
schema.logic.rules.push({id:'bonus',name:'Start bonus',enabled:true,event:{type:'game_start'},conditions:[],actions:[{type:'add_score',value:35}]});
await request('/games',{method:'POST',body:{schema},status:401});
const draft=(await request('/games',{method:'POST',cookie:a.cookie,body:{schema},status:201})).data;
await request('/games/'+draft.id,{status:404});
await request('/games/'+draft.id,{cookie:b.cookie,status:404});
const feed=(await request('/feed')).data;assert(!feed.games.some(g=>g.id===draft.id));
const pub=(await request('/games/'+draft.id,{method:'PUT',cookie:a.cookie,body:{schema,revision:draft.revision,isPublished:true}})).data;
await request('/games/'+draft.id,{method:'PUT',cookie:b.cookie,body:{schema,revision:pub.revision},status:403});
await request('/games/'+draft.id,{method:'PUT',cookie:a.cookie,body:{schema,revision:draft.revision},status:409});
await request('/games/'+draft.id,{method:'PUT',cookie:a.cookie,body:{schema:{...schema,scene:{...schema.scene,gridSize:0}},revision:pub.revision},status:400});
await request('/games',{method:'POST',cookie:a.cookie,headers:{Origin:'https://evil.invalid'},body:{schema},status:403});
await request('/games/no-such-game',{status:404});
await request('/scores',{method:'POST',cookie:a.cookie,body:{gameId:draft.id,value:999999999},status:404});
const run=(await request('/runs',{method:'POST',cookie:a.cookie,body:{gameId:draft.id},status:201})).data;
await request('/runs/'+run.id+'/finish',{method:'POST',body:{token:'forged',ticks:3,inputLog:[]},status:404});
await request('/runs/'+run.id+'/finish',{method:'POST',cookie:a.cookie,body:{token:run.token,ticks:1,inputLog:[],value:999999},status:422});
await request('/runs/'+run.id+'/finish',{method:'POST',cookie:a.cookie,body:{token:run.token,ticks:3,inputLog:[{tick:-1,keys:[]}]},status:400});
const finish=(await request('/runs/'+run.id+'/finish',{method:'POST',cookie:a.cookie,body:{token:run.token,ticks:3,inputLog:[],value:999999},status:201})).data;
assert.equal(finish.score,35);assert.equal(finish.ranked,true);
await request('/runs/'+run.id+'/finish',{method:'POST',cookie:a.cookie,body:{token:run.token,ticks:3,inputLog:[]},status:409});
const lb=(await request('/leaderboards/'+draft.slug)).data;assert.equal(lb.scores.length,1);assert.equal(Number(lb.scores[0].value),35);
await request('/clips',{method:'POST',cookie:b.cookie,body:{replayId:finish.replayId},status:404});
const clip=(await request('/clips',{method:'POST',cookie:a.cookie,body:{replayId:finish.replayId},status:201})).data;
await request('/clips/'+clip.id);
const remix=(await request('/remix/'+pub.id,{method:'POST',cookie:b.cookie,body:{},status:201})).data;
assert.equal(remix.remix_of_id,pub.id);assert.equal(remix.is_published,false);
let tree=(await request('/remix/tree/'+pub.id)).data;assert.equal(tree.children.length,0);
const remixPub=(await request('/games/'+remix.id,{method:'PUT',cookie:b.cookie,body:{schema:{...remix.schema,soundtrack:'chill'},isPublished:true,revision:remix.revision}})).data;
tree=(await request('/remix/tree/'+pub.slug)).data;assert.equal(tree.children[0].id,remix.id);
assert.equal((await request('/remix/tree/'+remix.id)).data.parent.id,pub.id);
const profile=(await request('/u/'+b.data.user.username)).data;
assert(profile.createdGames.some(g=>g.id===remix.id));assert(!profile.createdGames.some(g=>g.id===pub.id));
await request('/reports',{method:'POST',body:{gameId:pub.id,reason:'Test report'},status:401});
await request('/reports',{method:'POST',cookie:b.cookie,body:{gameId:pub.id,reason:'Automated moderation flow check'},status:201});
await request('/admin/reports',{cookie:b.cookie,status:403});
// Editing a game isolates previous scores while preserving old shared replays.
await request('/games/'+pub.id,{method:'PUT',cookie:a.cookie,body:{schema:{...pub.schema,title:'Updated '+suffix},isPublished:true,revision:pub.revision}});
assert.equal((await request('/leaderboards/'+pub.id)).data.scores.length,0);
assert.equal((await request('/clips/'+clip.id)).data.schema_snapshot.title,pub.title);
await request('/auth/logout',{method:'POST',cookie:a.cookie,body:{}});
assert.equal((await request('/auth/me',{cookie:a.cookie})).data.user,null);
await request('/auth/login',{method:'POST',body:{username:a.data.user.username,password:'incorrect password'},status:401});
const recovered=(await request('/auth/recover',{method:'POST',body:{username:a.data.user.username,recoveryCode:a.data.recoveryCode,password:password+'new'}})).data;
assert(recovered.recoveryCode);
await request('/auth/recover',{method:'POST',body:{username:a.data.user.username,recoveryCode:a.data.recoveryCode,password:password+'new'},status:401});
await request('/auth/login',{method:'POST',body:{username:a.data.user.username,password:password+'new'}});
if(process.env.TEST_ADMIN_USER){
 const adminName=process.env.TEST_ADMIN_USER;
 await request('/auth/signup',{method:'POST',body:{username:adminName,password},status:409});
 const credentials=JSON.parse(execFileSync(process.execPath,['dist/backend/src/createAdmin.js',adminName],{encoding:'utf8'}));
 const adminAccount=await request('/auth/login',{method:'POST',body:{username:adminName,password:credentials.password}});
 const reports=(await request('/admin/reports',{cookie:adminAccount.cookie})).data.reports;
 const report=reports.find(r=>r.game_id===pub.id);assert(report);
 await request('/admin/reports/'+report.id,{method:'POST',cookie:adminAccount.cookie,body:{action:'hide'}});
 await request('/games/'+pub.id,{status:404});
 await request('/clips/'+clip.id,{status:404});
 const html=await fetch(origin+'/game/'+pub.slug);assert.equal(html.status,404);
 const clipHtml=await fetch(origin+'/clip/'+clip.id);assert.equal(clipHtml.status,404);
}
console.log(JSON.stringify({status:'PASS',httpChecks:checks,verifiedScore:finish.score,coverage:['ownership','private drafts','CSRF','validation','missing resources','optimistic concurrency','forged and duplicate scores','replay access','remix attribution','profile isolation','reports','game revisions','clip snapshots','logout','account recovery']},null,2));
