import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.TEST_ORIGIN || 'http://localhost:3001';
const output = process.env.TEST_OUTPUT || '/tmp/gamio-browser-results';
await mkdir(output,{recursive:true});
const browser = await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{}),args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();const errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')console.log('BROWSER:',m.text());});
const suffix=Date.now().toString(36),username='tester_'+suffix,password='Orbit River Lantern '+suffix;
try {
 await page.goto(base+'/signup?next=/create');
 await page.getByLabel('Username',{exact:true}).fill(username);
 await page.getByLabel('Password',{exact:true}).fill(password);
 await page.getByRole('button',{name:'Create account',exact:true}).click();
 await page.getByRole('heading',{name:'Save your recovery code'}).waitFor();
 await page.getByRole('button',{name:'I saved my code — continue'}).click();
 await page.getByRole('button',{name:/Runner Jump hazards/}).click();
 await page.getByLabel('Game title').waitFor();
 const editUrl=page.url();
 await page.getByLabel('Game title').fill('Night Circuit '+suffix);
 await page.getByLabel('Game description').fill('Jump neon hazards and collect sparks. Beat my run, then remix the soundtrack.');
 await page.getByLabel('Soundtrack').selectOption('arcade');
 await page.getByRole('button',{name:'💾 Save',exact:true}).click();
 await page.getByText('💾 Saved!',{exact:true}).last().waitFor();
 await page.reload();
 assert.equal(await page.getByLabel('Game title').inputValue(),'Night Circuit '+suffix);
 assert.equal(await page.getByLabel('Soundtrack').inputValue(),'arcade');
 // An unreachable API must never be presented as a successful save.
 await page.getByLabel('Game description').fill('Unsaved change for the offline check.');
 await page.route('**/api/games/*',route=>route.abort('failed'));
 await page.getByRole('button',{name:'💾 Save',exact:true}).click();
 await page.getByText(/Not saved:/).last().waitFor();
 await page.unroute('**/api/games/*');
 await page.getByRole('button',{name:'💾 Save',exact:true}).click();
 await page.getByText('💾 Saved!',{exact:true}).last().waitFor();
 // World navigation reaches objects outside the initial 800-pixel viewport.
 await page.getByLabel('Select scene object').selectOption({label:'Goal · 3900, 356'});
 await page.getByLabel('X',{exact:true}).waitFor();
 assert.equal(Number(await page.getByLabel('X',{exact:true}).inputValue()),3900);
 await page.getByLabel('Select scene object').selectOption('');
 await page.getByLabel('Max Lives',{exact:true}).press('ArrowRight');
 await page.getByRole('button',{name:'💾 Save',exact:true}).click();
 await page.getByText('💾 Saved!',{exact:true}).last().waitFor();
 await page.screenshot({path:output+'/editor.png',fullPage:true});
 await page.getByRole('button',{name:'🚀 Publish',exact:true}).click();
 await page.waitForURL('**/game/**');
 const gameUrl=page.url();
 await page.getByRole('button',{name:'▶ Start run',exact:true}).click();
 await page.getByRole('heading',{name:/points. Who can beat it/}).waitFor({timeout:40000});
 await page.getByText('Verified. Your score is on the board.',{exact:true}).waitFor();
 assert.equal(errors.length,0,errors.join('\n'));
 await page.getByRole('button',{name:'Watch replay',exact:true}).click();
 await page.getByRole('button',{name:'Download gameplay video',exact:true}).click();
 await page.getByText('Video ready and downloaded. Your clip page now includes the video.',{exact:true}).waitFor({timeout:40000});
 await page.screenshot({path:output+'/game.png',fullPage:true});
 const clipUrl=new URL(await page.getByRole('link',{name:'Open your shareable clip page →'}).getAttribute('href'),base).href;
 await page.goto(clipUrl);
 await page.locator('video').waitFor();
 await page.locator('video').evaluate(v=>new Promise((resolve,reject)=>{if(v.readyState>=1)return resolve();v.onloadedmetadata=resolve;v.onerror=()=>reject(new Error('Video metadata failed'));}));
 const clipHtml=await (await context.request.get(clipUrl)).text();
 assert.match(clipHtml,/og:video/);
 await page.getByRole('link',{name:'Beat this score ↗'}).click();
 assert.match(page.url(),/beat=\d+/);
 await page.getByRole('link',{name:'↻ Remix this game',exact:true}).click();
 await page.getByRole('button',{name:'Remix this game ↗',exact:true}).click();
 await page.getByLabel('Game title').waitFor();
 await page.getByLabel('Game title').fill('After Hours '+suffix);
 await page.getByLabel('Soundtrack').selectOption('chill');
 await page.getByRole('button',{name:'🚀 Publish',exact:true}).click();
 await page.waitForURL('**/game/**');
 await page.getByText('Original:',{exact:false}).waitFor();
 await page.getByRole('link',{name:'Full leaderboard →'}).click();
 await page.waitForURL('**/leaderboard/**');
 await page.reload();
 await page.getByRole('heading',{name:'Leaderboard',exact:true}).waitFor();
 await page.goto(base+'/dashboard');
 await page.getByRole('heading',{name:'My games',exact:true}).waitFor();
 await page.goto(editUrl);
 await page.getByLabel('Game title').waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.getByLabel('Select scene object').selectOption({label:'Player · 80, 380'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Editor overflows mobile viewport');
 await page.screenshot({path:output+'/mobile-editor.png',fullPage:true});
 await page.setViewportSize({width:1440,height:1000});
 await page.goto(base+'/u/'+username);
 await page.getByRole('heading',{name:'@'+username,exact:true}).waitFor();
 // Independent visitor: deep links, video, and protected draft editing.
 const visitor=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 const mobile=await visitor.newPage();mobile.on('pageerror',e=>errors.push(e.message));
 await mobile.goto(gameUrl);await mobile.getByRole('button',{name:'▶ Start run'}).waitFor();
 assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Game page overflows mobile viewport');
 await mobile.screenshot({path:output+'/mobile-game.png',fullPage:true});
 await mobile.getByRole('button',{name:'▶ Start run'}).click();
 await mobile.getByRole('heading',{name:/points. Who can beat it/}).waitFor({timeout:40000});
 await mobile.getByText('Run saved. Sign in before your next run to join the leaderboard.',{exact:true}).waitFor();
 await mobile.goto(clipUrl);await mobile.locator('video').waitFor();
 await mobile.goto(base+'/');await mobile.locator('.game-card').first().waitFor();
 assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Home page overflows mobile viewport');
 await mobile.screenshot({path:output+'/mobile-home.png',fullPage:true});
 await visitor.close();
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({status:'PASS',username,gameUrl,clipUrl,checks:['signup','recovery-code','draft-save-reload','publish','server-verified-score','replay','video-render-upload-playback','OG-tags','score-challenge','remix-soundtrack-lineage','leaderboard-deep-link','profile','dashboard','anonymous-play','mobile-layout'],screenshots:output},null,2));
} catch(e) {await page.screenshot({path:output+'/failure.png',fullPage:true});console.error('URL',page.url());console.error((await page.locator('body').innerText()).slice(-5000));throw e;}
finally {await browser.close();}
